In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("myntra_products_catalog.csv")

In [3]:
df

,ProductID,ProductName,ProductBrand,Gender,Price (INR),NumImages,Description,PrimaryColor
0,10017413,DKNY Unisex Black & Grey Printed Medium Trolle...,DKNY,Unisex,11745,7,"Black and grey printed medium trolley bag, sec...",Black
1,10016283,EthnoVogue Women Beige & Grey Made to Measure ...,EthnoVogue,Women,5810,7,Beige & Grey made to measure kurta with churid...,Beige
2,10009781,SPYKAR Women Pink Alexa Super Skinny Fit High-...,SPYKAR,Women,899,7,Pink coloured wash 5-pocket high-rise cropped ...,Pink
3,10015921,Raymond Men Blue Self-Design Single-Breasted B...,Raymond,Men,5599,5,Blue self-design bandhgala suitBlue self-desig...,Blue
4,10017833,Parx Men Brown & Off-White Slim Fit Printed Ca...,Parx,Men,759,5,"Brown and off-white printed casual shirt, has ...",White
...,...,...,...,...,...,...,...,...
12486,10262843,Pepe Jeans Men Black Hammock Slim Fit Low-Rise...,Pepe Jeans,Men,1299,7,"Black dark wash 5-pocket low-rise jeans, clean...",Black
12487,10261721,Mochi Women Gold-Toned Solid Heels,Mochi,Women,1990,5,"A pair of gold-toned open toe heels, has regul...",Gold
12488,10261607,612 league Girls Navy Blue & White Printed Reg...,612 league,Girls,602,4,Navy Blue and White printed mid-rise denim sho...,Blue
12489,10266621,Bvlgari Men Aqva Pour Homme Marine Eau de Toil...,Bvlgari,Men,8950,2,Bvlgari Men Aqva Pour Homme Marine Eau de Toil...,NaN
12490,10265199,Pepe Jeans Men Black & Grey Striped Polo Colla...,Pepe Jeans,Men,799,5,"Black and grey striped T-shirt, has a polo col...",Black

In [4]:
xyz=df.sample(n=1000,random_state=42)

In [5]:
xyz

,ProductID,ProductName,ProductBrand,Gender,Price (INR),NumImages,Description,PrimaryColor
10105,10247147,Flying Machine Boys Blue Regular Fit Mid-Rise ...,Flying Machine,Boys,749,3,Blue medium wash five-pocket mid-rise jeans wi...,Blue
4667,10134531,Indian Terrain Boys Yellow Printed Round Neck ...,Indian Terrain,Boys,314,3,"Yellow printed T-shirt, has a round neck, and ...",Yellow
7523,10186043,AURELIA Women Mustard Yellow Regular Fit Solid...,AURELIA,Women,899,5,Mustard yellow solid mid-rise cropped trousers...,Yellow
7420,10186599,Lavie Orange Textured Shoulder Bag,Lavie,Women,2384,6,"Orange textured shoulder bag, has a zip closur...",Red
11193,10252497,Genius18 Men White & Navy Blue Printed Hooded ...,Genius18,Men,874,5,"White and Navy Blue printed sweatshirt, has a ...",Blue
...,...,...,...,...,...,...,...,...
7772,10178975,Global Desi Navy Blue Textured Shoulder Bag,Global Desi,Women,1559,8,"Navy Blue textured shoulder bag, has a button ...",Blue
5526,10138367,Indian Terrain Boys Turquoise & Navy Blue Regu...,Indian Terrain,Boys,719,7,"Turquoise and navy blue checked casual shirt, ...",Blue
11763,10252837,PUMA Motorsport Unisex Blue Printed Red Bull R...,PUMA Motorsport,Unisex,3999,7,Special Technologies:IGNITE: PUMA's foam midso...,Blue
7317,10177629,SG YUVRAJ Boys Blue & Brown Sherwani Set,SG YUVRAJ,Boys,1479,5,This Sherwani set consists of a sherwani and a...,Blue
5250,10138679,Indian Terrain Boys Blue Striped Cotton Regula...,Indian Terrain,Boys,629,4,"Blue striped casual shirt, has a spread collar...",Blue

In [9]:
shejal=df.sample(frac=0.2, random_state=42)

In [10]:
shejal

,ProductID,ProductName,ProductBrand,Gender,Price (INR),NumImages,Description,PrimaryColor
10105,10247147,Flying Machine Boys Blue Regular Fit Mid-Rise ...,Flying Machine,Boys,749,3,Blue medium wash five-pocket mid-rise jeans wi...,Blue
4667,10134531,Indian Terrain Boys Yellow Printed Round Neck ...,Indian Terrain,Boys,314,3,"Yellow printed T-shirt, has a round neck, and ...",Yellow
7523,10186043,AURELIA Women Mustard Yellow Regular Fit Solid...,AURELIA,Women,899,5,Mustard yellow solid mid-rise cropped trousers...,Yellow
7420,10186599,Lavie Orange Textured Shoulder Bag,Lavie,Women,2384,6,"Orange textured shoulder bag, has a zip closur...",Red
11193,10252497,Genius18 Men White & Navy Blue Printed Hooded ...,Genius18,Men,874,5,"White and Navy Blue printed sweatshirt, has a ...",Blue
...,...,...,...,...,...,...,...,...
6076,10161227,Indian Terrain Men Black Rust Red Solid Revers...,Indian Terrain,Men,1799,5,"Black and Rust Red solid reversible jacket, ha...",Red
5556,10137271,Puma Unisex Grey Escaper Core Running Shoes,Puma,Unisex,2974,5,Special Technology:SOFTFOAM+ Comfort gives you...,Grey
10366,10243575,GAP Women V-neck Floral Print Flutter Sleeve Top,GAP,Women,1149,5,"Smooth, lightweight, flowy weaveSlightly sheer...",NaN
4617,10129579,Newport Men Off-White Printed Round Neck T-shirt,Newport,Men,479,5,"Off-white and Brown printed T-shirt, has a rou...",White
409,10017571,Soie Nude Lace Non-Wired Non Padded full cover...,Soie,Women,988,5,Nude lace full-coverage Everyday braNon Padded...,Red

In [14]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\singh\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.4.1)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 1.2 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/8.0 MB 1.2 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.0 MB 1.2 MB/s eta 0:00:06
   ------ --------------------------------- 1.3/8.0 MB 1.2 MB/s eta 0:00:06
   ------- -------------------------------- 1.6/8.0 MB 1.2 MB/s eta 0:00:06
   --------- ------------------------------ 1.8/8.0 MB 1.2 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.0 MB 1.2 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.0 MB 1.2 MB/s eta 0:00:05
   -------------- ------------------------- 2.9/8.0 MB 1.3 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.0 MB 1.4 MB/s eta 0:00:04
   ------------------ --------------------- 3.7/8.0 MB 1.4 MB/s eta 0:00:04
   ------------------- -------------------- 3.9/8.0 MB 1.5 MB/s eta 0:00:03
   ---------------------- ----------------- 4.5/8.0 MB 1.5 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.0 MB 1.6 MB/s eta 0:00:02
   -------------------------- ------------- 5.2/8.0 MB 1.6 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.0 MB 1.6 MB/s eta 0:00:02
   ------------------------------ --------- 6.0/8.0 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 6.6/8.0 MB 1.6 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.0 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 1.7 MB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.0-cp312-cp312-win_amd64.whl (36.3 MB)
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   - -------------------------------------- 1.0/36.3 MB 2.6 MB/s eta 0:00:14
   - -------------------------------------- 1.6/36.3 MB 2.7 MB/s eta 0:00:13
   -- ------------------------------------- 2.4/36.3 MB 2.9 MB/s eta 0:00:12
   --- ------------------------------------ 2.9/36.3 MB 3.0 MB/s eta 0:00:12
   ---- ----------------------------------- 3.7/36.3 MB 3.1 MB/s eta 0:00:11
   ---- ----------------------------------- 4.5/36.3 MB 3.2 MB/s eta 0:00:11
   ----- ---------------------------------- 5.2/36.3 MB 3.2 MB/s eta 0:00:10
   ------ --------------------------------- 6.0/36.3 MB 3.3 MB/s eta 0:00:10
   ------- -------------------------------- 6.6/36.3 MB 3.3 MB/s eta 0:00:10
   -------- ------------------------------- 7.3/36.3 MB 3.3 MB/s eta 0:00:09
   -------- ------------------------------- 8.1/36.3 MB 3.3 MB/s eta 0:00:09
   ---------- ----------------------------- 9.2/36.3 MB 3.4 MB/s eta 0:00:08
   ---------- ----------------------------- 10.0/36.3 MB 3.4 MB/s eta 0:00:08
   ----------- ---------------------------- 10.7/36.3 MB 3.5 MB/s eta 0:00:08
   ------------ --------------------------- 11.5/36.3 MB 3.5 MB/s eta 0:00:08
   ------------- -------------------------- 12.6/36.3 MB 3.6 MB/s eta 0:00:07
   -------------- ------------------------- 13.4/36.3 MB 3.6 MB/s eta 0:00:07
   --------------- ------------------------ 14.4/36.3 MB 3.7 MB/s eta 0:00:06
   ---------------- ----------------------- 15.2/36.3 MB 3.7 MB/s eta 0:00:06
   ----------------- ---------------------- 16.3/36.3 MB 3.7 MB/s eta 0:00:06
   ------------------- -------------------- 17.3/36.3 MB 3.8 MB/s eta 0:00:06
   -------------------- ------------------- 18.4/36.3 MB 3.8 MB/s eta 0:00:05
   --------------------- ------------------ 19.4/36.3 MB 3.9 MB/s eta 0:00:05
   ---------------------- ----------------- 20.7/36.3 MB 4.0 MB/s eta 0:00:04
   ----------------------- ---------------- 21.8/36.3 MB 4.0 MB/s eta 0:00:04
   ------------------------- -------------- 23.1/36.3 MB 4.1 MB/s eta 0:00:04
   -------------------------- ------------- 24.4/36.3 MB 4.2 MB/s eta 0:00:03
   ---------------------------- ----------- 25.7/36.3 MB 4.2 MB/s eta 0:00:03
   ------------------------------ --------- 27.3/36.3 MB 4.3 MB/s eta 0:00:03
   ------------------------------- -------- 28.8/36.3 MB 4.4 MB/s eta 0:00:02
   --------------------------------- ------ 30.4/36.3 MB 4.6 MB/s eta 0:00:02
   ----------------------------------- ---- 32.0/36.3 MB 4.6 MB/s eta 0:00:01
   ------------------------------------- -- 33.8/36.3 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  35.7/36.3 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 36.3/36.3 MB 4.9 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from scipy.stats import ttest_ind

In [ ]:
#t-test
male=df[df["Gender"]=="Men"]["Price (INR)"]
female=df[df["Gender"]=="Women"]["Price (INR)"]

In [20]:
p_value=ttest_ind(male,female)

In [22]:
print(t_state,p_value)

5.7602052995914255 TtestResult(statistic=np.float64(5.7602052995914255), pvalue=np.float64(8.65658884544324e-09), df=np.float64(9715.0))

In [23]:
from scipy.stats import norm #for z-test

In [25]:
price=df["Price (INR)"]

In [49]:
sample=price.mean()
avg_price=1400
real_data=price.std(ddof=0)
n=len(price)

In [50]:
z=(sample-avg_price)/(real_data/np.sqrt(n))
z

np.float64(2.778276360876003)

In [51]:
from scipy.stats import chi2_contingency

In [52]:
con=pd.crosstab(df["ProductBrand"],df["Gender"])

In [53]:
chi2,p,dof,expected=chi2_contingency(con)
chi2,p

(np.float64(39658.50801851147), np.float64(0.0))